### ISSUE TITLE
Unknown Dependency: TeddyDD.fish

### ISSUE THREAD

**Issue by jonasbb** [lunaryorn/vscode-fish-ide#4]
I freshly installed your extension from the marketplace. In the dependencies tab it is showing this error message `Unknown Dependency: TeddyDD.fish`. It seems the extension was unpublished.

**Comment by lunaryorn** [comment]
Oh I wasn’t aware.  Do you happen to know at alternative?

**Comment by lunaryorn** [comment]
Looks like there's https://github.com/aaronsky/fish-vscode.  I asked its maintainer whether we can depend on it instead.

**Comment by lunaryorn** [comment]
I haven't got any reply, but to keep this extension working I now use fish-vscode as dependency.

At some point we should perhaps provide our own syntax support instead of depending on others.
