### ISSUE TITLE
how to ignore files?

### ISSUE THREAD

**Issue by edouard-lopez** [lunaryorn/vscode-fish-ide#6]
**related:** jorgebucaran/fishtape#32

---

`fish_indent` [broke my `fishtape` tests](https://github.com/jorgebucaran/fishtape/issues/32) when reformatting.

Is there a way to ignore some file, _e.g._ `*.test.fish`?

**Comment by lunaryorn** [comment]
You can disable formatting for such files in workspace settings, can’t you?

**Comment by edouard-lopez** [comment]
Adding this to my workspace's config disable formatting for every `fish` file:

```json
{
  "[fish]": {
    "editor.formatOnSave": false
  },
  "editor.formatOnSave": true
}
```

Doesn't seems to support glob/patterns.

**Comment by lunaryorn** [comment]
Doesn’t it?  I thought it would 🤷‍♂️

Anyhow I don’t think that I’d like to have a special case in this extension.

Please raise the issue with fish shell, to get fish indent fixed, and ask the VSCode folks whether and how to configure per file settings.
